# This is a skeleton Travis CI config file that provides a starting point for adding CI
# to a Python project. Since we primarily develop in python3, this skeleton config file
# will be specific to that language.
#
# See https://config.travis-ci.com/ for a full list of configuration options.

os: linux

dist: xenial

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

# Scripts to run at install stage
install: ./configure --dev

# Scripts to run at script stage
script: venv/bin/pytest
