
################################################################################
# We use  Appveyor to run minimal smoke tests suites on Pythons 3.x
# on Windows 64 bits
################################################################################
environment:
    matrix:
        - PYTHON: "C:\\Python36-x64"
#        - PYTHON: "C:\\Python37-x64"
#        - PYTHON: "C:\\Python38-x64"
#        - PYTHON: "C:\\Python39-x64"


build: off


test_script:
    - python -c "import sys;print(sys.getdefaultencoding())"
    - cmd: "set PYTHON_EXECUTABLE=%PYTHON%\\python.exe && configure --dev && venv\\Scripts\\pytest -vvs tests"
