################################################################################
# We use Azure to run the full tests suites on multiple Python 3.x
# on multiple Windows, macOS and Linux versions all on 64 bits
# These jobs are using VMs with Azure-provided Python builds
################################################################################

jobs:
  - template: etc/ci/azure-posix.yml
    parameters:
      job_name: ubuntu20_cpython
      image_name: ubuntu-20.04
      python_versions: ["3.7", "3.8", "3.9", "3.10", "3.11"]
      test_suites:
        all: venv/bin/pytest -n 2 -vvs

  - template: etc/ci/azure-posix.yml
    parameters:
      job_name: ubuntu22_cpython
      image_name: ubuntu-22.04
      python_versions: ["3.7", "3.8", "3.9", "3.10", "3.11"]
      test_suites:
        all: venv/bin/pytest -n 2 -vvs

  - template: etc/ci/azure-posix.yml
    parameters:
      job_name: macos11_cpython
      image_name: macOS-11
      python_versions: ["3.7", "3.8", "3.9", "3.10", "3.11"]
      test_suites:
        all: venv/bin/pytest -n 2 -vvs

  - template: etc/ci/azure-posix.yml
    parameters:
      job_name: macos12_cpython
      image_name: macOS-12
      python_versions: ["3.7", "3.8", "3.9", "3.10", "3.11"]
      test_suites:
        all: venv/bin/pytest -n 2 -vvs

  - template: etc/ci/azure-posix.yml
    parameters:
      job_name: macos13_cpython
      image_name: macOS-13
      python_versions: ["3.7", "3.8", "3.9", "3.10", "3.11"]
      test_suites:
        all: venv/bin/pytest -n 2 -vvs

  - template: etc/ci/azure-win.yml
    parameters:
      job_name: win2019_cpython
      image_name: windows-2019
      python_versions: ["3.7", "3.8", "3.9", "3.10", "3.11"]
      test_suites:
        all: venv\Scripts\pytest -n 2 -vvs

  - template: etc/ci/azure-win.yml
    parameters:
      job_name: win2022_cpython
      image_name: windows-2022
      python_versions: ["3.7", "3.8", "3.9", "3.10", "3.11"]
      test_suites:
        all: venv\Scripts\pytest -n 2 -vvs
