
################################################################################
# We use Azure to run the full tests suites on multiple Python 3.x
# on multiple Windows, macOS and Linux versions all on 64 bits
# These jobs are using VMs with Azure-provided Python builds
################################################################################

jobs:

    - template: etc/ci/azure-posix.yml
      parameters:
          job_name: ubuntu18_cpython
          image_name: ubuntu-18.04
          python_versions: ['3.6', '3.7', '3.8', '3.9', '3.10']
          test_suites:
              all: venv/bin/pytest -n 2 -vvs

    - template: etc/ci/azure-posix.yml
      parameters:
          job_name: ubuntu20_cpython
          image_name: ubuntu-20.04
          python_versions: ['3.6', '3.7', '3.8', '3.9', '3.10']
          test_suites:
              all: venv/bin/pytest -n 2 -vvs

    - template: etc/ci/azure-posix.yml
      parameters:
          job_name: macos1015_cpython
          image_name: macos-10.15
          python_versions: ['3.6', '3.7', '3.8', '3.9', '3.10']
          test_suites:
              all: venv/bin/pytest -n 2 -vvs

    - template: etc/ci/azure-posix.yml
      parameters:
          job_name: macos11_cpython
          image_name: macos-11
          python_versions: ['3.7', '3.8', '3.9', '3.10']
          test_suites:
              all: venv/bin/pytest -n 2 -vvs

    - template: etc/ci/azure-win.yml
      parameters:
          job_name: win2019_cpython
          image_name: windows-2019
          python_versions: ['3.6', '3.7', '3.8', '3.9', '3.10']
          test_suites:
              all: venv\Scripts\pytest -n 2 -vvs

    - template: etc/ci/azure-win.yml
      parameters:
          job_name: win2022_cpython
          image_name: windows-2022
          python_versions: ['3.7', '3.8', '3.9', '3.10']
          test_suites:
              all: venv\Scripts\pytest -n 2 -vvs
